"""Seed the finance.subscriptions table with real subscription data.

Derived from HSBC/Monzo transaction analysis + email receipts (March 2026).
Run once to populate, then tweak via the dashboard UI.

Usage:
    cd Discord-Messenger
    python scripts/subscriptions/seed_subscriptions.py
"""

import os
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from dotenv import load_dotenv
load_dotenv()

import httpx

SUPABASE_URL = os.getenv("SUPABASE_URL")
API_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY") or os.getenv("SUPABASE_KEY")
REST = f"{SUPABASE_URL}/rest/v1"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Accept-Profile": "finance",
    "Content-Profile": "finance",
    "Prefer": "return=representation,resolution=merge-duplicates",
}


# ============================================================================
# SUBSCRIPTION DATA — derived from actual bank transactions + email receipts
# ============================================================================

SUBSCRIPTIONS = [
    # ── PERSONAL: Entertainment & Streaming ──────────────────────────────
    {
        "name": "Netflix",
        "provider": "Netflix",
        "scope": "personal",
        "category": "Entertainment",
        "amount": 12.99,
        "frequency": "monthly",
        "billing_day": 5,
        "payment_method": "HSBC via PayPal",
        "bank_description_pattern": "PAYPAL *NETFLIX",
        "status": "active",
        "start_date": "2025-01-06",
        "notes": "Was 10.99 until Apr 2025",
    },
    {
        "name": "Disney+",
        "provider": "Disney",
        "scope": "personal",
        "category": "Entertainment",
        "amount": 9.99,
        "frequency": "monthly",
        "billing_day": 20,
        "payment_method": "HSBC via PayPal",
        "bank_description_pattern": "PAYPAL *DISNEYPLUS",
        "status": "active",
        "start_date": "2025-01-20",
        "notes": "Was 8.99 until Nov 2025",
    },
    {
        "name": "YouTube Premium",
        "provider": "Google",
        "scope": "personal",
        "category": "Entertainment",
        "amount": 12.99,
        "frequency": "monthly",
        "billing_day": 9,
        "payment_method": "HSBC",
        "bank_description_pattern": "Google YouTube London",
        "status": "active",
        "start_date": "2025-02-05",
    },
    {
        "name": "Spotify Family",
        "provider": "Spotify",
        "scope": "personal",
        "category": "Entertainment",
        "amount": 21.99,
        "frequency": "monthly",
        "billing_day": 6,
        "payment_method": "HSBC",
        "bank_description_pattern": "Spotify Limited London",
        "status": "active",
        "start_date": "2025-01-06",
    },
    {
        "name": "Discovery+",
        "provider": "Discovery",
        "scope": "personal",
        "category": "Entertainment",
        "amount": 30.99,
        "frequency": "annual",
        "billing_day": 19,
        "payment_method": "HSBC",
        "bank_description_pattern": "Discovery +",
        "status": "active",
        "start_date": "2025-01-29",
        "next_renewal_date": "2027-01-19",
        "notes": "Annual charge ~Jan",
    },
    {
        "name": "Swoopa",
        "provider": "Swoopa",
        "scope": "personal",
        "category": "Entertainment",
        "amount": 35.00,
        "frequency": "monthly",
        "billing_day": 11,
        "payment_method": "HSBC via Google Play",
        "bank_description_pattern": "Google Play Apps London",
        "status": "active",
        "start_date": "2025-09-11",
        "notes": "Penny auction app",
    },
    {
        "name": "Amazon Kids+",
        "provider": "Amazon",
        "scope": "personal",
        "category": "Family",
        "amount": 4.99,
        "frequency": "monthly",
        "billing_day": 7,
        "payment_method": "HSBC",
        "bank_description_pattern": "amazon.co.uk - Amazon Kids",
        "status": "active",
        "start_date": "2026-01-07",
    },
    {
        "name": "Amazon Prime",
        "provider": "Amazon",
        "scope": "personal",
        "category": "Shopping",
        "amount": 8.99,
        "frequency": "monthly",
        "billing_day": 26,
        "payment_method": "HSBC",
        "bank_description_pattern": "Amazon Prime*",
        "status": "active",
        "start_date": "2025-01-27",
    },

    # ── PERSONAL: AI / Tech Platforms ────────────────────────────────────
    {
        "name": "Claude Max",
        "provider": "Anthropic",
        "scope": "personal",
        "category": "AI & Tech",
        "amount": 180.00,
        "frequency": "monthly",
        "billing_day": 13,
        "payment_method": "HSBC",
        "bank_description_pattern": "CLAUDE.AI SUBSCRIP",
        "status": "active",
        "plan_tier": "Max",
        "start_date": "2025-12-01",
        "notes": "x20 usage. Amount varies with exchange rate",
        "url": "https://claude.ai",
    },
    {
        "name": "Anthropic API Credits",
        "provider": "Anthropic",
        "scope": "personal",
        "category": "AI & Tech",
        "amount": 18.00,
        "frequency": "monthly",
        "payment_method": "HSBC",
        "bank_description_pattern": "ANTHROPIC ANTHROPIC.COM",
        "status": "active",
        "notes": "Usage-based, avg ~$24/mo. Varies.",
        "url": "https://console.anthropic.com",
    },
    {
        "name": "OpenAI ChatGPT",
        "provider": "OpenAI",
        "scope": "personal",
        "category": "AI & Tech",
        "amount": 8.90,
        "frequency": "monthly",
        "payment_method": "HSBC",
        "bank_description_pattern": "OPENAI",
        "status": "active",
        "notes": "Was 20/mo (Plus), appears reduced Jan 2026 — maybe downgraded",
        "url": "https://chat.openai.com",
    },
    {
        "name": "xAI Grok",
        "provider": "xAI",
        "scope": "personal",
        "category": "AI & Tech",
        "amount": 7.40,
        "frequency": "monthly",
        "billing_day": 27,
        "payment_method": "HSBC",
        "bank_description_pattern": "XAI LLC",
        "status": "active",
        "notes": "$10 USD",
        "url": "https://x.ai",
    },
    {
        "name": "Moonshot AI (Kimi)",
        "provider": "Moonshot AI",
        "scope": "personal",
        "category": "AI & Tech",
        "amount": 7.33,
        "frequency": "monthly",
        "billing_day": 28,
        "payment_method": "HSBC",
        "bank_description_pattern": "MOONSHOT AI",
        "status": "active",
        "notes": "$10 USD. Only 1 charge visible — may be new or one-off",
    },
    {
        "name": "ElevenLabs",
        "provider": "ElevenLabs",
        "scope": "personal",
        "category": "AI & Tech",
        "amount": 9.82,
        "frequency": "monthly",
        "billing_day": 2,
        "payment_method": "HSBC",
        "bank_description_pattern": "ELEVENLABS",
        "status": "active",
        "notes": "$1 USD Starter plan equivalent — check actual tier",
        "url": "https://elevenlabs.io",
    },
    {
        "name": "Google One (Storage)",
        "provider": "Google",
        "scope": "personal",
        "category": "AI & Tech",
        "amount": 1.59,
        "frequency": "monthly",
        "billing_day": 19,
        "payment_method": "HSBC",
        "bank_description_pattern": "GOOGLE *Google One g.co",
        "status": "active",
        "plan_tier": "100GB",
    },
    {
        "name": "Google AI Pro (Gemini)",
        "provider": "Google",
        "scope": "personal",
        "category": "AI & Tech",
        "amount": 18.99,
        "frequency": "monthly",
        "billing_day": 14,
        "payment_method": "HSBC",
        "bank_description_pattern": "Google One London",
        "status": "active",
        "plan_tier": "AI Premium",
        "notes": "Billed as Google One but is Gemini AI Pro",
    },

    # ── PERSONAL: Household / Utilities ──────────────────────────────────
    {
        "name": "Sky Digital",
        "provider": "Sky",
        "scope": "personal",
        "category": "TV & Internet",
        "amount": 46.00,
        "frequency": "monthly",
        "billing_day": 22,
        "payment_method": "HSBC DD",
        "bank_description_pattern": "SKY DIGITAL",
        "status": "active",
    },
    {
        "name": "NOW TV Sports",
        "provider": "NOW TV",
        "scope": "personal",
        "category": "TV & Internet",
        "amount": 34.99,
        "frequency": "monthly",
        "billing_day": 29,
        "payment_method": "HSBC via PayPal",
        "bank_description_pattern": "PAYPAL *NOW",
        "status": "active",
        "notes": "Sky Sports day pass / monthly",
    },
    {
        "name": "NOW TV Boost",
        "provider": "NOW TV",
        "scope": "personal",
        "category": "TV & Internet",
        "amount": 6.00,
        "frequency": "monthly",
        "billing_day": 29,
        "payment_method": "HSBC via PayPal",
        "bank_description_pattern": "PAYPAL *NOW",
        "status": "active",
        "notes": "Ultra add-on for NOW",
    },
    {
        "name": "TV Licence",
        "provider": "TV Licensing",
        "scope": "personal",
        "category": "TV & Internet",
        "amount": 14.95,
        "frequency": "monthly",
        "billing_day": 15,
        "payment_method": "HSBC DD",
        "bank_description_pattern": "TV LICENCE MBP",
        "status": "active",
    },
    {
        "name": "Octopus Energy",
        "provider": "Octopus Energy",
        "scope": "personal",
        "category": "Utilities",
        "amount": 175.65,
        "frequency": "monthly",
        "billing_day": 5,
        "payment_method": "HSBC DD",
        "bank_description_pattern": "OCTOPUS ENERGY",
        "status": "active",
        "notes": "Gas + electricity",
    },
    {
        "name": "South East Water",
        "provider": "South East Water",
        "scope": "personal",
        "category": "Utilities",
        "amount": 75.00,
        "frequency": "monthly",
        "billing_day": 7,
        "payment_method": "HSBC DD",
        "bank_description_pattern": "SOUTH EAST WATER",
        "status": "active",
        "notes": "Was 84, dropped to 75 Dec 2025",
    },
    {
        "name": "Council Tax",
        "provider": "Tonbridge & Malling",
        "scope": "personal",
        "category": "Utilities",
        "amount": 288.00,
        "frequency": "monthly",
        "billing_day": 5,
        "payment_method": "HSBC DD",
        "bank_description_pattern": "TONBRIDGE AND MAL",
        "status": "active",
        "notes": "10 months per year (Apr-Jan)",
    },
    {
        "name": "Home Insurance",
        "provider": "Homeprotect",
        "scope": "personal",
        "category": "Insurance",
        "amount": 286.05,
        "frequency": "annual",
        "billing_day": 20,
        "payment_method": "HSBC",
        "bank_description_pattern": "HOMEPROTECT",
        "status": "active",
        "start_date": "2026-01-20",
        "next_renewal_date": "2027-01-20",
    },
    {
        "name": "Three Mobile (H3G)",
        "provider": "Three",
        "scope": "personal",
        "category": "Phone",
        "amount": 15.50,
        "frequency": "monthly",
        "billing_day": 22,
        "payment_method": "HSBC DD",
        "bank_description_pattern": "H3G",
        "status": "active",
        "notes": "Primary mobile contract",
    },
    {
        "name": "Talkmobile",
        "provider": "Talkmobile",
        "scope": "personal",
        "category": "Phone",
        "amount": 7.80,
        "frequency": "monthly",
        "billing_day": 2,
        "payment_method": "HSBC DD",
        "bank_description_pattern": "TALKMOBILE",
        "status": "active",
        "notes": "Second phone line",
    },
    {
        "name": "Cleaner (Linda)",
        "provider": "Linda Nieman",
        "scope": "personal",
        "category": "Household",
        "amount": 55.00,
        "frequency": "fortnightly",
        "payment_method": "HSBC Bank Transfer",
        "bank_description_pattern": "Linda Nieman",
        "status": "active",
    },

    # ── PERSONAL: Kids Activities (term-based) ───────────────────────────
    {
        "name": "Piano (Sofia Pagoni)",
        "provider": "Sofia Pagoni",
        "scope": "personal",
        "category": "Kids Activities",
        "amount": 220.00,
        "frequency": "termly",
        "payment_method": "HSBC Bank Transfer",
        "bank_description_pattern": "Sofia Pagoni",
        "status": "active",
        "notes": "Varies per term ~200-260",
    },
    {
        "name": "Swimming (Water Wise)",
        "provider": "Water Wise",
        "scope": "personal",
        "category": "Kids Activities",
        "amount": 270.00,
        "frequency": "termly",
        "payment_method": "HSBC Bank Transfer",
        "bank_description_pattern": "Water Wise",
        "status": "active",
        "notes": "Emmie & Max. Varies ~210-294",
    },
    {
        "name": "Tutor (Mrs Thurgood)",
        "provider": "Mrs C A Thurgood",
        "scope": "personal",
        "category": "Kids Activities",
        "amount": 156.00,
        "frequency": "termly",
        "payment_method": "HSBC Bank Transfer",
        "bank_description_pattern": "Mrs C A Thurgood",
        "status": "active",
        "notes": "Emmie",
    },
    {
        "name": "Trinity Dance",
        "provider": "Trinity Dance",
        "scope": "personal",
        "category": "Kids Activities",
        "amount": 36.00,
        "frequency": "termly",
        "payment_method": "HSBC",
        "bank_description_pattern": "TRINITY DANCE",
        "status": "active",
        "notes": "Emmie",
    },
    {
        "name": "Beavers",
        "provider": "Scouts",
        "scope": "personal",
        "category": "Kids Activities",
        "amount": 50.00,
        "frequency": "termly",
        "payment_method": "HSBC Bank Transfer",
        "bank_description_pattern": "Beavers",
        "status": "active",
        "notes": "Max",
    },
    {
        "name": "Brownies",
        "provider": "Girlguiding",
        "scope": "personal",
        "category": "Kids Activities",
        "amount": 50.00,
        "frequency": "termly",
        "payment_method": "HSBC Bank Transfer",
        "bank_description_pattern": "Brownies",
        "status": "active",
        "notes": "Emmie. Varies 35-60",
    },
    {
        "name": "Chess Club",
        "provider": "Learn Chess",
        "scope": "personal",
        "category": "Kids Activities",
        "amount": 198.00,
        "frequency": "termly",
        "payment_method": "HSBC Bank Transfer",
        "bank_description_pattern": "Learn Chess",
        "status": "active",
        "notes": "Emmie & Max. Varies 130-208",
    },

    # ── PERSONAL: Possibly cancelled ─────────────────────────────────────
    {
        "name": "Strava",
        "provider": "Strava",
        "scope": "personal",
        "category": "Fitness",
        "amount": 8.99,
        "frequency": "monthly",
        "payment_method": "HSBC",
        "bank_description_pattern": "StravaCOM",
        "status": "cancelled",
        "end_date": "2025-04-29",
        "notes": "Last charge Apr 2025 — appears cancelled",
    },
    {
        "name": "Audible",
        "provider": "Amazon",
        "scope": "personal",
        "category": "Entertainment",
        "amount": 109.99,
        "frequency": "annual",
        "payment_method": "HSBC",
        "bank_description_pattern": "Audible UK",
        "status": "active",
        "start_date": "2025-06-06",
        "next_renewal_date": "2026-06-06",
        "notes": "Was monthly 17.99, then 109.99 lump in Jun 2025 — switched to annual",
    },

    # ── BUSINESS: Hadley Bricks ──────────────────────────────────────────
    {
        "name": "Supabase Pro",
        "provider": "Supabase",
        "scope": "business",
        "category": "Infrastructure",
        "amount": 27.00,
        "frequency": "monthly",
        "billing_day": 19,
        "payment_method": "HSBC",
        "bank_description_pattern": "SUPABASE SINGAPORE",
        "status": "active",
        "notes": "~$35 USD. Hosts HB inventory + Second Brain + financial data",
        "url": "https://supabase.com/dashboard",
    },
    {
        "name": "Vercel Pro",
        "provider": "Vercel",
        "scope": "business",
        "category": "Infrastructure",
        "amount": 14.89,
        "frequency": "monthly",
        "billing_day": 23,
        "payment_method": "HSBC",
        "bank_description_pattern": "VERCEL INC",
        "status": "active",
        "notes": "$20 USD. Hosts HB web app",
        "url": "https://vercel.com/dashboard",
    },
    {
        "name": "Google Cloud",
        "provider": "Google",
        "scope": "business",
        "category": "Infrastructure",
        "amount": 21.44,
        "frequency": "monthly",
        "billing_day": 2,
        "payment_method": "HSBC",
        "bank_description_pattern": "Google CLOUD",
        "status": "active",
        "notes": "Usage-based. Gemini API, Cloud Run etc.",
        "url": "https://console.cloud.google.com",
    },
    {
        "name": "Shopify",
        "provider": "Shopify",
        "scope": "business",
        "category": "Platform Fees",
        "amount": 25.00,
        "frequency": "monthly",
        "payment_method": "HSBC",
        "bank_description_pattern": "SHOPIFY*",
        "status": "active",
        "notes": "Basic plan. Last visible charge Apr 2025 — may be PayPal now",
    },
    {
        "name": "Amazon Seller Central",
        "provider": "Amazon",
        "scope": "business",
        "category": "Platform Fees",
        "amount": 30.00,
        "frequency": "monthly",
        "payment_method": "Deducted from payouts",
        "status": "active",
        "notes": "Deducted from Amazon balance before payout — not visible in bank",
    },
    {
        "name": "eBay Store",
        "provider": "eBay",
        "scope": "business",
        "category": "Platform Fees",
        "amount": 35.00,
        "frequency": "monthly",
        "payment_method": "Deducted from payouts",
        "status": "active",
        "notes": "Deducted from eBay managed payments — not visible in bank",
    },
]


def main():
    print(f"Seeding {len(SUBSCRIPTIONS)} subscriptions...")

    with httpx.Client(timeout=30) as client:
        for sub in SUBSCRIPTIONS:
            resp = client.post(
                f"{REST}/subscriptions",
                headers=HEADERS,
                json=sub,
            )
            if resp.status_code >= 400:
                print(f"  FAIL: {sub['name']} — {resp.status_code}: {resp.text[:200]}")
            else:
                print(f"  OK: {sub['name']}")

    print("\nDone!")


if __name__ == "__main__":
    main()
