-- Migration: Fitness Exercise Media
-- Adds video links, step-by-step instructions, and equipment info to the
-- exercise library so the dashboard can render a full reference page.
--
-- video_url points at a YouTube search URL (not a specific video ID) because:
--   1. Search URLs never rot — YouTube always returns live results.
--   2. Chris can replace them with direct video IDs later if he wants.
--   3. It avoids hardcoding third-party video IDs that can disappear.

ALTER TABLE fitness_exercises
    ADD COLUMN IF NOT EXISTS video_url TEXT,
    ADD COLUMN IF NOT EXISTS instructions TEXT,
    ADD COLUMN IF NOT EXISTS equipment TEXT;

-- Populate via a bulk UPDATE ... FROM VALUES for all 37 seeded exercises.
UPDATE fitness_exercises AS e SET
    video_url    = v.video_url,
    instructions = v.instructions,
    equipment    = v.equipment
FROM (VALUES
-- ═════════════════════════ PUSH ═════════════════════════
('push-up',
 'https://www.youtube.com/results?search_query=push+up+proper+form+tutorial',
 E'1. Start in high plank, hands under shoulders, body straight.\n2. Brace core, squeeze glutes, ribs down.\n3. Lower chest toward floor, elbows at 45°.\n4. Press back up to full lockout.\n5. 3x10, +2 reps/week, then elevate feet for harder variation.',
 'None'),
('incline-push-up',
 'https://www.youtube.com/results?search_query=incline+push+up+beginner',
 E'1. Hands on sturdy surface (kitchen counter, sofa edge, stairs).\n2. Body in straight line from head to heels.\n3. Lower chest to the surface slowly (2s down).\n4. Press back up, keep core tight.\n5. Progress by lowering the incline week by week.',
 'Sturdy raised surface'),
('pike-push-up',
 'https://www.youtube.com/results?search_query=pike+push+up+form',
 E'1. Start in downward dog: hips high, legs straight, hands shoulder-width.\n2. Lower head toward hands, elbows tucked.\n3. Press back to start.\n4. Keep hips high throughout — don''t let them drop.\n5. Progresses to wall-supported handstand push-up.',
 'None'),
('chair-dip',
 'https://www.youtube.com/results?search_query=chair+dip+triceps+form',
 E'1. Sit on edge of chair, hands grip the edge next to hips.\n2. Slide hips off the chair, legs extended or bent.\n3. Lower until elbows reach 90°, shoulders stay down.\n4. Press back up through palms.\n5. Progress by straightening legs, then elevating feet.',
 'Sturdy chair'),
('diamond-push-up',
 'https://www.youtube.com/results?search_query=diamond+push+up+triceps',
 E'1. Hands form a diamond (thumbs + index fingers touching) under chest.\n2. Elbows track close to the ribs, not flared.\n3. Lower chest to hands, maintain plank.\n4. Press back up.\n5. Tougher than standard push-up — scale with incline if needed.',
 'None'),

-- ═════════════════════════ PULL ═════════════════════════
('inverted-row',
 'https://www.youtube.com/results?search_query=inverted+row+under+table+bodyweight',
 E'1. Lie under a sturdy table, grip the edge shoulder-width.\n2. Straighten body, heels on floor, arms extended.\n3. Pull chest to the table edge, squeeze shoulder blades.\n4. Lower with control.\n5. Progress: elevate feet, or find a lower bar.',
 'Sturdy table or low bar'),
('superman-hold',
 'https://www.youtube.com/results?search_query=superman+hold+lower+back',
 E'1. Lie face down, arms extended overhead.\n2. Simultaneously lift arms, chest, and legs off the floor.\n3. Squeeze glutes and lower back.\n4. Hold — neck neutral, don''t crane up.\n5. 3 x 20s, +5s/week.',
 'None'),
('reverse-snow-angel',
 'https://www.youtube.com/results?search_query=reverse+snow+angel+rear+delt',
 E'1. Lie face down, arms at sides, palms down (thumbs up).\n2. Lift arms a few inches off the floor.\n3. Slowly sweep them overhead (like a snow angel).\n4. Return to start with control.\n5. Slow tempo — this is a rear-delt activator, not a volume move.',
 'None'),
('y-t-w-raise',
 'https://www.youtube.com/results?search_query=ytw+raise+prone+rear+delt',
 E'1. Lie face down, arms extended overhead forming a Y.\n2. Lift arms, hold 2s, lower.\n3. Move arms to T position (straight out), lift, hold 2s, lower.\n4. Move to W (elbows bent, hands by shoulders), lift, hold, lower.\n5. That''s 1 rep. Chin tucked throughout.',
 'None'),
('prone-i-hold',
 'https://www.youtube.com/results?search_query=prone+I+hold+upper+back',
 E'1. Lie face down, arms straight overhead (palms facing each other).\n2. Lift arms and chest slightly off the floor.\n3. Hold — squeeze upper back, arms stay straight.\n4. Breathe normally — don''t hold breath.\n5. 3 x 30s, +5s/week.',
 'None'),

-- ═════════════════════════ LEGS A (quad focus) ═════════════════════════
('bw-squat',
 'https://www.youtube.com/results?search_query=bodyweight+squat+form',
 E'1. Feet shoulder-width, toes slightly out.\n2. Hinge at hips, sit back and down.\n3. Knees track over toes, chest up.\n4. Go below parallel if mobility allows.\n5. Drive through heels to stand. Pause 2s at bottom for progression.',
 'None'),
('reverse-lunge',
 'https://www.youtube.com/results?search_query=reverse+lunge+form',
 E'1. Stand tall, hands on hips.\n2. Step one foot back, lower until both knees at 90°.\n3. Front knee over ankle, back knee hovers just above floor.\n4. Drive through front heel to stand.\n5. Alternate legs. +1 rep/week.',
 'None'),
('wall-sit',
 'https://www.youtube.com/results?search_query=wall+sit+form',
 E'1. Back flat against a wall, feet ~60cm from wall.\n2. Slide down until thighs parallel to floor (90° knees).\n3. Keep back flat, core braced.\n4. Hold. Don''t rest hands on thighs.\n5. +10s/week. Burns — embrace it.',
 'Wall'),
('bulgarian-split-squat',
 'https://www.youtube.com/results?search_query=bulgarian+split+squat+bodyweight',
 E'1. Rear foot elevated on a chair behind you.\n2. Front foot planted a stride length forward.\n3. Lower the rear knee toward the floor.\n4. Keep front knee tracking over ankle.\n5. Drive through front heel. 8 reps/side, +1/week.',
 'Chair or sofa'),
('step-up',
 'https://www.youtube.com/results?search_query=step+up+bodyweight+chair',
 E'1. Place one foot flat on a sturdy chair or step.\n2. Drive through the heel, stand tall on top.\n3. Lower the trailing leg back down with control — no bouncing.\n4. Alternate legs.\n5. Full extension at the top for glute activation.',
 'Sturdy chair'),

-- ═════════════════════════ LEGS B (posterior chain) ═════════════════════════
('glute-bridge',
 'https://www.youtube.com/results?search_query=glute+bridge+form',
 E'1. Lie on back, knees bent, feet flat.\n2. Drive heels into the floor, lift hips.\n3. Squeeze glutes hard at the top — 1s hold.\n4. Lower with control.\n5. Progress to single-leg when 3x15 feels easy.',
 'None'),
('single-leg-glute-bridge',
 'https://www.youtube.com/results?search_query=single+leg+glute+bridge',
 E'1. Lie on back, one foot flat, other leg straight out.\n2. Drive through the planted heel, lift hips.\n3. Keep hips level (don''t let one side sag).\n4. Squeeze glute, hold 1s, lower.\n5. 8 reps/leg, +1/week.',
 'None'),
('bw-good-morning',
 'https://www.youtube.com/results?search_query=bodyweight+good+morning+hamstrings',
 E'1. Stand tall, hands behind head or crossed on chest.\n2. Hinge at hips (not waist), push butt back.\n3. Keep back flat, slight knee bend.\n4. Lower until you feel a hamstring stretch.\n5. Drive hips forward to stand. Slow tempo (3s down).',
 'None'),
('single-leg-rdl',
 'https://www.youtube.com/results?search_query=single+leg+romanian+deadlift+bodyweight',
 E'1. Stand on one leg, slight bend.\n2. Hinge forward, opposite leg extends straight back.\n3. Body forms a straight line from head to heel at the bottom.\n4. Keep back flat, hips square.\n5. Drive through standing heel to return. 8/leg, +1/week.',
 'None'),
('calf-raise',
 'https://www.youtube.com/results?search_query=calf+raise+form',
 E'1. Stand tall, feet hip-width apart.\n2. Rise up onto the balls of your feet.\n3. Pause 1s at the top, squeeze calves.\n4. Lower slowly (2s) for full ROM.\n5. Progress to single-leg when 3x20 is easy.',
 'Wall for balance (optional)'),

-- ═════════════════════════ CORE ═════════════════════════
('plank',
 'https://www.youtube.com/results?search_query=plank+proper+form',
 E'1. Forearms on the floor, elbows under shoulders.\n2. Body in a straight line from head to heels.\n3. Squeeze glutes, brace abs (like bracing for a punch).\n4. Don''t sag, don''t pike hips.\n5. Breathe. 3 x 45s, +10s/week.',
 'None'),
('side-plank',
 'https://www.youtube.com/results?search_query=side+plank+form',
 E'1. Lie on one side, forearm on floor, elbow under shoulder.\n2. Stack feet, lift hips off the floor.\n3. Body in a straight line, hips stacked.\n4. Free arm on hip or extended up.\n5. 2 x 30s each side, +5s/week.',
 'None'),
('dead-bug',
 'https://www.youtube.com/results?search_query=dead+bug+exercise',
 E'1. Lie on back, arms straight up, knees bent at 90°.\n2. Press lower back into floor.\n3. Slowly extend opposite arm and leg toward the floor.\n4. Return, alternate sides.\n5. Keep lower back glued to the floor — that''s the whole point.',
 'None'),
('bird-dog',
 'https://www.youtube.com/results?search_query=bird+dog+form',
 E'1. Start on hands and knees, wrists under shoulders.\n2. Extend opposite arm and leg simultaneously.\n3. Hold 2s — no hip rotation.\n4. Return and alternate.\n5. Slow and controlled, no wobbling.',
 'None'),
('hollow-hold',
 'https://www.youtube.com/results?search_query=hollow+body+hold',
 E'1. Lie on back, arms overhead, legs straight.\n2. Press lower back into the floor.\n3. Lift shoulders and legs slightly off the floor.\n4. Body forms a shallow banana.\n5. Hold. 3 x 20s, +5s/week. Brutal — scale by bending knees.',
 'None'),
('mountain-climber',
 'https://www.youtube.com/results?search_query=mountain+climber+exercise',
 E'1. Start in high plank, hands under shoulders.\n2. Drive one knee to chest, then quickly switch.\n3. Keep hips low — don''t pike.\n4. Fast tempo (this is conditioning + core).\n5. 3 x 20 reps (total, both legs).',
 'None'),

-- ═════════════════════════ CONDITIONING ═════════════════════════
('burpee',
 'https://www.youtube.com/results?search_query=burpee+proper+form',
 E'1. Stand tall, drop hands to floor.\n2. Jump feet back to plank.\n3. Optional: push-up.\n4. Jump feet forward to hands.\n5. Jump up with arms overhead. That''s 1 rep. Land soft, knees bent.',
 'None'),
('jumping-jack',
 'https://www.youtube.com/results?search_query=jumping+jack+form',
 E'1. Stand tall, feet together, arms at sides.\n2. Jump: feet out wide, arms overhead.\n3. Jump back: feet together, arms down.\n4. Steady rhythm — this is a warm-up, not a finisher.\n5. 2 x 30.',
 'None'),
('high-knees',
 'https://www.youtube.com/results?search_query=high+knees+exercise',
 E'1. Stand tall, run in place.\n2. Drive each knee up to waist height.\n3. Arms pump like running.\n4. Stay on balls of feet, land softly.\n5. 3 x 30s. Works as a finisher or warm-up.',
 'None'),
('skater-jump',
 'https://www.youtube.com/results?search_query=skater+jump+lateral',
 E'1. Stand on one leg, slight bend.\n2. Jump laterally to the other leg, landing soft.\n3. Back leg crosses behind, like a speed skater.\n4. Use arms for momentum.\n5. 12 reps total. +2/week.',
 'None'),

-- ═════════════════════════ MOBILITY ═════════════════════════
('cat-cow',
 'https://www.youtube.com/results?search_query=cat+cow+stretch+spine',
 E'1. Start on hands and knees, wrists under shoulders.\n2. Inhale: drop belly, lift chest and tailbone (cow).\n3. Exhale: round spine, tuck chin and tailbone (cat).\n4. Move slowly with the breath.\n5. 10 slow reps. Warms up the spine.',
 'None'),
('worlds-greatest-stretch',
 'https://www.youtube.com/results?search_query=worlds+greatest+stretch',
 E'1. Start in a push-up position.\n2. Step right foot outside right hand (deep lunge).\n3. Rotate torso right, reach right arm to ceiling.\n4. Return hand, step back, switch sides.\n5. 3 reps each side. Opens hips + thoracic spine.',
 'None'),
('couch-stretch',
 'https://www.youtube.com/results?search_query=couch+stretch+hip+flexor',
 E'1. Kneel in front of a sofa or wall.\n2. Rear foot up against the wall (toes pointing up).\n3. Front foot flat, knee at 90°.\n4. Squeeze rear glute, push hips forward.\n5. 45s each side. Opens tight hip flexors from sitting.',
 'Wall or sofa'),
('pigeon-pose',
 'https://www.youtube.com/results?search_query=pigeon+pose+hip+stretch',
 E'1. From all fours, bring right knee forward behind right wrist.\n2. Extend left leg straight back, hips square to floor.\n3. Walk hands forward, lower chest toward the floor.\n4. Breathe into the right hip.\n5. 60s each side. Releases deep glute/hip tension.',
 'None'),
('thoracic-twist',
 'https://www.youtube.com/results?search_query=thoracic+rotation+stretch',
 E'1. Kneel on all fours, one hand behind head.\n2. Rotate elbow down toward opposite hand.\n3. Then rotate up toward ceiling, open chest.\n4. Follow with eyes.\n5. 5 reps each side. Frees mid-back rotation.',
 'None'),
('childs-pose',
 'https://www.youtube.com/results?search_query=childs+pose+yoga',
 E'1. Kneel on floor, big toes touching, knees wide.\n2. Sit hips back onto heels.\n3. Fold forward, arms extended long in front.\n4. Forehead to floor, breathe into lower back.\n5. 60s. A full-body reset.',
 'None'),
('neck-rolls',
 'https://www.youtube.com/results?search_query=neck+rolls+mobility',
 E'1. Sit or stand tall, shoulders relaxed.\n2. Drop chin toward chest.\n3. Slowly roll right ear to right shoulder.\n4. Continue back and around — one full circle.\n5. 5 circles each direction. No forcing — slow and soft.',
 'None')
) AS v(slug, video_url, instructions, equipment)
WHERE e.slug = v.slug;
